### ISSUE TITLE
[v2.2] Site needs favicon

### ISSUE THREAD

**Issue by websupergirl** [EugeneCodeCamp/EugeneCodeCamp.github.io#11]

**Comment by ZeroProtagonist** [comment]
Hi, I've got a question about this one: does the site not already have a favicon? Or is this a request for something else (the one it has looks good, imo). 

I was well into working on this issue when I realized it already had one, and I went ahead and replaced it on my local branch just to see if I could, but frankly mine doesn't look as good as the one it already has. 

So I guess I'm asking for some clarification for what this issue is seeking. Thanks! 

Jason

**Comment by websupergirl** [comment]
The current favicon is the default one from nuxt.js. You can try something like this?

![ecc](https://user-images.githubusercontent.com/38568655/79895384-a8a91e00-83bb-11ea-9d7b-dec9680189e9.png)

**Comment by ZeroProtagonist** [comment]
I did it with this lol
![ECC_favicon_64](https://user-images.githubusercontent.com/55775542/79896635-78627f00-83bd-11ea-9b7c-97e00c2ee99e.png)

Is that one way too big?

**Comment by websupergirl** [comment]
It has to be like ... 16x16 so that probably is.

**Comment by websupergirl** [comment]
Closed by https://github.com/EugeneCodeCamp/EugeneCodeCamp.github.io/pull/37
